server:
  port: 8083

spring:
  data:
    mongodb:
      database: RestaurantApp
      uri: mongodb+srv://root:root@tweetapp.v00ihzx.mongodb.net/RestaurantApp
  social:
    facebook:
      appId: 546100497690700
      appSecret: 876423b0b9f410c2f5ef665096fae120
  
  security:
    oauth2:
      client:
        registration:          
          google:
            clientId: 459334269929-69k1rfm2snegoeparfavhfkof5gg3l0j.apps.googleusercontent.com
            clientSecret: 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
            
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
        preferIpAddress: true
  
google:
  clientId: 84327651763-g6d73dojmkdb24qcnl9pniq0dd5rc5o8.apps.googleusercontent.com
  apiKey: AIzaSyDALoi5z4JPIMLRli2ROpWuTEWpzHEHTuU

stripe:
  apiKey: sk_test_51NEvZ0SEyC5CQIOhFHSLLwrkDbIwLJmFcR99WQoCowQZql4pwsO2IjyLYVDU5PVihp47KgpRr2glZAsxHcG6znYu007hhM6GzZ

razorpay:
  secretId: rzp_test_iIK24lb6Jfiw1d
  secretKey: jPnZBzdunoEp3VGad6gbw2ft

review:
  service:
    URL: http://localhost:8082
  
#logging:
#  file:
#    name: userservice.log

management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
  health:
    circuitbreakers:
      enabled: true
resilience4j:
  circuitbreaker:
    instances:
      review-service:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

      
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
