server:
  port: 8081

spring:
  data:
    mongodb:
      database: RestaurantApp
      uri: mongodb+srv://root:root@tweetapp.v00ihzx.mongodb.net/RestaurantApp
  social:
    facebook:
      appId: 546100497690700
      appSecret: 876423b0b9f410c2f5ef665096fae120
  
  security:
    oauth2:
      client:
        registration:          
          google:
            clientId: 459334269929-69k1rfm2snegoeparfavhfkof5gg3l0j.apps.googleusercontent.com
            clientSecret: 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
            
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
        preferIpAddress: true
  
google:
  clientId: 84327651763-g6d73dojmkdb24qcnl9pniq0dd5rc5o8.apps.googleusercontent.com
  apiKey: AIzaSyDALoi5z4JPIMLRli2ROpWuTEWpzHEHTuU
      
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

jwt:
  secret: 'amma ki kadai - secret key for cloud kitchen app'
